#!/usr/bin/env bash

set -e
echo "install_weak_deps=False" | tee -a /etc/dnf/dnf.conf

dnf install -y \
    gdm \
    wget \
    gnome-terminal \
    nautilus \
    google-noto-sans-thai-fonts \
    google-noto-sans-cjk-fonts \
    tar \
    google-noto-serif-cjk-fonts \
    google-noto-serif-thai-fonts \
    pipewire-pulseaudio \
    nodejs \
    npm

dnf remove -y \
    gnome-tour \
    malcontent-control \
    gnome-remote-desktop \
    vim-minimal


dnf install -y plymouth-system-theme

plymouth-set-default-theme -R bgrt

echo "Installing Steam..."
dnf install glibc.i686 mesa-libGL.i686 libdrm.i686 libnsl.i686 tar -y
wget https://repo.steampowered.com/steam/archive/stable/steam_latest-stable.tar.gz
wget https://github.com/TimeAndTimeStudio/Fedora-Install/raw/refs/heads/main/steam/icons.tar.xz

tar -xvf steam_latest-stable.tar.gz
cd steam-launcher
rm steam
mv bin_steam.sh steam
mv steam /usr/bin/
mkdir -p ~/.local/share/applications
mv steam.desktop ~/.local/share/applications/steam.desktop
chmod +x ~/.local/share/applications/steam.desktop
mkdir /usr/lib/steam
mv bootstraplinux_ubuntu12_32.tar.xz /usr/lib/steam/
cd ../
tar -xvf icons.tar.xz
cp -r icons/* /usr/share/icons/hicolor/
rm icons.tar.xz steam_latest-stable.tar.gz
rm -r steam-launcher icons

echo "Installing Brave Origin..."
dnf config-manager addrepo --from-repofile=https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
dnf install brave-origin -y

echo "Installing Wallpaper..."
wget https://github.com/TimeAndTimeStudio/Fedora-Install/releases/download/App-id-1/019b913a-a484-7237-b907-2444e37e22e2.png
wget https://github.com/TimeAndTimeStudio/Fedora-Install/releases/download/App-id-1/horizontal.pic.jpg

npm install -g tmg-studio
npm install -g tma-agent

systemctl set-default graphical.target
gtk-update-icon-cache -f /usr/share/icons/hicolor
sed -i 's/^GRUB_TIMEOUT=.*/GRUB_TIMEOUT=0/' /etc/default/grub
sed -i '1i GRUB_TIMEOUT_STYLE=hidden' /etc/default/grub
grub2-mkconfig -o /boot/grub2/grub.cfg
