#!/bin/bash

MESA_PREFIX="/opt/mesa"

export PATH="$MESA_PREFIX/bin:$PATH"

export LD_LIBRARY_PATH="$MESA_PREFIX/lib64"

export LIBGL_DRIVERS_PATH="$MESA_PREFIX/lib64/dri"

export LIBVA_DRIVERS_PATH="$MESA_PREFIX/lib64/dri"

export VK_DRIVER_FILES="$MESA_PREFIX/share/vulkan/icd.d"

export PKG_CONFIG_PATH="$MESA_PREFIX/lib64/pkgconfig:$PKG_CONFIG_PATH"

exec "$@"
