#!/bin/bash

MESA_PREFIX="$HOME/mesa-install/usr"

export PATH="$MESA_PREFIX/bin:$PATH"

export LD_LIBRARY_PATH="$MESA_PREFIX/lib64"

export LIBGL_DRIVERS_PATH="$MESA_PREFIX/lib64/dri"

export LIBVA_DRIVERS_PATH="$MESA_PREFIX/lib64/dri"

# ให้ Vulkan หา AMD + Intel ICD เอง
export VK_DRIVER_FILES="$MESA_PREFIX/share/vulkan/icd.d/radeon_custom.json"

export PKG_CONFIG_PATH="$MESA_PREFIX/lib64/pkgconfig"

exec "$@"
